Reworks the tvdb-authenticate and tvdb-get-request to have better error handling and generally clean up the script.

diff --git a/src/utilities/tvdb-authenticate b/src/utilities/tvdb-authenticate
--- a/src/utilities/tvdb-authenticate
+++ b/src/utilities/tvdb-authenticate
@@ -1,27 +1,29 @@
 #!/bin/bash
+set -euo pipefail
 
 CACHED_TOKEN_DIRECTORY="/tmp/usr/tvdb-cache"
 CACHED_TOKEN_FILE="$CACHED_TOKEN_DIRECTORY/.tvdb-token-cache"
 
-if [[ -z $1 ]]; then
-	echo "ERROR: no API key provided."
-	exit 1
-fi
+api_key="${1:?ERROR - No API token provided.}"
 
 if [[ -e "$CACHED_TOKEN_FILE" ]]; then
-	secondsSinceTokenCacheUpdated=$(( $(date +%s) - $(date -r $CACHED_TOKEN_FILE +%s) ))
-	if [[ $secondsSinceTokenCacheUpdated -lt "84000" ]]; then
+	seconds_since_token_cache_updated=$(( $(date +%s) - $(date -r $CACHED_TOKEN_FILE +%s) ))
+	if [[ $seconds_since_token_cache_updated -lt "84000" ]]; then
 		cat "$CACHED_TOKEN_FILE"
 		exit 0
 	fi
 fi
 
-loginUrl="https://api.thetvdb.com/login"
-acceptJsonHeader="Accept: application/json"
-jsonContentHeader="Content-Type: application/json"
+response=$(curl --silent -X POST --header "accept: application/json" --header "Content-Type: application/json" -d "{ \"apikey\": \"$api_key\" }" "https://api4.thetvdb.com/v4/login")
 
-rawJson=$(curl --silent -X POST --header "$acceptJsonHeader" --header "$jsonContentHeader" -d "{ \"apikey\":\"$1\" }" "$loginUrl")
-token=$(echo "$rawJson" | jq -r ".token")
+if jq -e '.status != "success"' <<< "$response" > /dev/null; then
+	echo "ERROR - failure trying to authenticate. Message = '$(jq -r '.message' <<< "$response")'."
+	exit 1
+fi
 
-mkdir -p "$CACHED_TOKEN_DIRECTORY" && echo "$token" > "$CACHED_TOKEN_FILE"
+token=$(jq -r '.data.token' <<< "$response")
+
+mkdir -p "$CACHED_TOKEN_DIRECTORY"
+(umask 077; echo "$token" > "$CACHED_TOKEN_FILE")
+
 echo "$token"
diff --git a/src/utilities/tvdb-get-request b/src/utilities/tvdb-get-request
--- a/src/utilities/tvdb-get-request
+++ b/src/utilities/tvdb-get-request
@@ -1,13 +1,14 @@
 #!/bin/bash
+set -euo pipefail
 
-if [[ -z $1 ]]; then
-	echo "ERROR: No API token provided."
+api_token="${1:?ERROR - No API token provided.}"
+api_path="${2:?ERROR - No API request URL provided.}"
+
+response=$(curl --silent -X GET --header "Accept: application/json" --header "Authorization: Bearer $api_token" "https://api4.thetvdb.com/v4$api_path")
+
+if jq -e '.status != "success"' <<< "$response" > /dev/null; then
+	echo "ERROR - Got failure response from TVDB. Message: $(jq -r '.message' <<< "$response")"
 	exit 1
 fi
 
-if [[ -z $2 ]]; then
-	echo "ERROR: No API request URL provided."
-	exit 1
-fi
-
-curl --silent -X GET --header "Accept: application/json" --header "Authorization: Bearer $1" "https://api.thetvdb.com$2"
+echo "$response"
